service: digitalpark

frameworkVersion: ">=1.7.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs6.10

functions:
  retrieveCoursesCatalog:
    handler: courses/catalog.handler
    events:
      - http:
          path: /courses-catalog
          method: get
  retrieveCourseDetail:
    handler: courses/detail.handler
    events:
      - http:
          path: /course-detail
          method: get


