service: digitalpark
frameworkVersion: ">=1.7.0 <2.0.0"

custom:
  stage: ${opt:stage, self:provider.stage}
  devDynamoCapacity:
    ReadCapacityUnits: 1
    WriteCapacityUnits: 1
  prodDynamoCapacity:
    ReadCapacityUnits: 5
    WriteCapacityUnits: 5

provider:
  name: aws
  runtime: nodejs6.10
  environment:
    SLS_STAGE: ${self:custom.stage}
    DPT_COURSES_CATALOG: {Ref: DigitalParkCatalogDB}
    DPT_COURSES: {Ref: DigitalParkCoursesDB}
    DPT_BLOG: {Ref: DigitalParkBlogDB}
  iamRoleStatements:
    - Action:
      - dynamodb:GetItem
      - dynamodb:Scan
      Resource: "arn:aws:dynamodb:us-east-1:*:*"
      Effect: Allow

functions:
  retrieveCoursesCatalog:
    handler: courses/catalog.handler
    events:
      - http:
          path: /courses
          method: get
  createCourse:
    handler: courses/create.handler
    events:
      - http:
          path: /courses
          method: post
  retrieveCourseDetail:
    handler: courses/detail.handler
    events:
      - http:
          path: /courses/{courseId}
          method: get
  retrieveBlogEntries:
    handler: blog/list.handler
    events:
      - http:
          path: /blogs
          method: get

resources:
  Resources:
    DigitalParkCatalogDB:
      Type: "AWS::DynamoDB::Table"
      Properties:
        AttributeDefinitions:
          - AttributeName: catecode
            AttributeType: S
        KeySchema:
          - AttributeName: catecode
            KeyType: HASH
        ProvisionedThroughput: ${self:custom.${self:custom.stage}DynamoCapacity}
        TableName: "${self:custom.stage}-digitalpark-courses-catalog"
    DigitalParkCoursesDB:
      Type: "AWS::DynamoDB::Table"
      Properties:
        AttributeDefinitions:
          - AttributeName: coursecode
            AttributeType: S
        KeySchema:
          - AttributeName: coursecode
            KeyType: HASH
        ProvisionedThroughput: ${self:custom.${self:custom.stage}DynamoCapacity}
        TableName: "${self:custom.stage}-digitalpark-courses"
    DigitalParkBlogDB:
      Type: "AWS::DynamoDB::Table"
      Properties:
        AttributeDefinitions:
          - AttributeName: coursecode
            AttributeType: S
        KeySchema:
          - AttributeName: coursecode
            KeyType: HASH
        ProvisionedThroughput: ${self:custom.${self:custom.stage}DynamoCapacity}
        TableName: "${self:custom.stage}-digitalpark-blog"