service: digitalpark

frameworkVersion: ">=1.7.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs6.10
  environment:
    SLS_STAGE: ${opt:stage, self:provider.stage}
  iamRoleStatements:
    - Action:
      - dynamodb:GetItem
      - dynamodb:Scan
      Resource: "arn:aws:dynamodb:us-east-1:470187922491:table/digitalpark-${opt:stage, self:provider.stage}-courses-catalog"
      Effect: Allow

functions:
  retrieveCoursesCatalog:
    handler: courses/catalog.handler
    events:
      - http:
          path: /courses
          method: get
  createCourse:
    handler: courses/create.handler
    events:
      - http:
          path: /courses
          method: post
  retrieveCourseDetail:
    handler: courses/detail.handler
    events:
      - http:
          path: /courses/{courseId}
          method: get
  retrieveBlogEntries:
    handler: blog/list.handler
    events:
      - http:
          path: /blogs
          method: get

resources:
  Resources:
    DigitalParkDB:
      Type: "AWS::DynamoDB::Table"
      Properties:
        AttributeDefinitions:
          - AttributeName: catecode
            AttributeType: S
        KeySchema:
          - AttributeName: catecode
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 2
          WriteCapacityUnits: 2
        TableName: "digitalpark-${opt:stage, self:provider.stage}-courses-catalog"
      
